[INFO-BEAMER]
pi-id = 1234
background-setup-id = 1234
background-setup-name = "foo"
talks-setup-id = 5678
talks-setup-name = "footalks"
# extron-port = 

[REDIS]
URL = "redis://redis:6379/0"

[EXTRON]
# URL = ""
# num-inputs =
