version: '3.7'

services:
  app:
    image: chaosdorf/freitagsfoo-web:latest
    build: .
    ports:
      - '5000:5000'
    secrets:
      - INFO_BEAMER_API_KEY
      - FFTALKS_SENTRY_DSN
    environment:
      - FLASK_APP=src/app.py
      - FLASK_DEBUG=1
    volumes:
      - ./config.toml:/etc/freitagsfoo-web.toml:ro
      - ./src:/opt/app/src:ro
    entrypoint: /usr/local/bin/flask run --host=0.0.0.0
  redis:
    image: redis:6-alpine

secrets:
  INFO_BEAMER_API_KEY:
    file: ./info-beamer-api-key
  FFTALKS_SENTRY_DSN:
    file: ./sentry-dsn
