version: '3.7'

services:
  app:
    image: chaosdorf/freitagsfoo-web:latest
    build: .
    ports:
      - '5000:5000'
    secrets:
      - INFO_BEAMER_API_KEY
      - FFTALKS_SENTRY_PYTHON_DSN
      - FFTALKS_SENTRY_JS_DSN
    environment:
      - FLASP_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./config.cfg:/etc/freitagsfoo-web.cfg:ro
      - ./src:/opt/app
    entrypoint: /usr/local/bin/flask run --host=0.0.0.0

secrets:
  INFO_BEAMER_API_KEY:
    file: ./info-beamer-api-key
  FFTALKS_SENTRY_PYTHON_DSN:
    file: ./sentry-python-dsn
  FFTALKS_SENTRY_JS_DSN:
    file: ./sentry-js-dsn
